### PR TITLE
Change the log output file

### PR DESCRIPTION
**Pull request by TuEmb**
Hi @sweihub,

I do like your crate, I want to make a PR to add new feature for updating log file path.
Could you help me review my changes to apply this ?

Thanks

### CODE REVIEW

**Comment by sweihub** [comment]
Hi @TuEmb 
Thanks for using the simple `log2` crate, and thanks for your PR, I reviewed the code, and I love to have PR for good features. I have some questions

1.  At the very begining, we use `log2::open("log.txt")` to open a file, full path is accepted, why do you want to change the `File` object when program is running?
2. You use `Log2::update(File)` to update the log target, maybe better name `redirect`, but, you simply update the `File` object, and not the initial file path, that will break the later file rotation, the next file will be written to initial file directory.

Would you explain? thanks!

**Comment by TuEmb** [comment]
Hi @sweihub , thanks for your feedback. Let me share you a little bit about my project.

1. I applied your crate into my project, I want to change the log file name and the path for every sessions of production line. Therefore, I can trace to log file of every product created. For example:
- Session 1:
       Name: product_1_2024_05_24_08-18-37.txt
       Path:    <project>/output/<product_1>/log/
- Session 2:
       Name: product_2_2024_05_24_09-22-33.txt
       Path:    <project>/output/<product_2>/log/
       
 2. yes, I will change from `update` to `redirect` to make clear the meaning. I want to ask, if I use the rotate feature.
 - At the beginning, the log store at:
       log/log.txt, log/log_1.txt, log/log_2.txt, ...
 - After that, I redirect to log_2/log.txt, will to store the log as: log_2/log.txt, log_2/log_1.txt, log_2/log_2.txt, ....
 
 Sorry, I haven't tried the rotation feature before.

**Comment by sweihub** [comment]
I got your points, it really breaks the rotation feature, you can set smaller file size to trigger the rotation feature, for example
```rust
let _log2 = log2::open("log.txt").size(256).start();
```

So in your scenario, your product globally share a single `log2` instance, and you want each of your session logs to different directory, you dynamically switch your logger target by changing the `File` object? If there are multiple threads, your sessions logs wil be messed up I guess?

If my understanding is right, and considering the Rust log facade, global macro (info, error, ...), I propose to encode the `session` identifier into the log line, the background logger should open multiple file for the sessions. The proposed format
```rust
let _log2 = log2::open("/path/to/[session]/log.txt");
info!("[1] This is for session 1");
debug!("[{}] This is for session {}", 2, 2);
```
The leading session placeholder `[n]` will be stripped and line will be written to corresponding session log.txt, do you agree?

**Comment by sweihub** [comment]
Answer to your question `#2`

> At the beginning, the log store at:
> log/log.txt, log/log_1.txt, log/log_2.txt, ...
> After that, I redirect to log_2/log.txt, will it store the log as: log_2/log.txt, log_2/log_1.txt, log_2/log_2.txt, .... ?
> 

1. At the beginning, the log store at: `log/log.txt`
2. After that, you redirect to `log2/log.txt`, and you are happy to write more logs
3. Now, rotation occurs, since the initial path was not changed, the later file will be `log/log.1.txt`

**Comment by TuEmb** [comment]
Ya, I got a demo for rotate feature as your guide. I think for flexible logging, we can put any valid paths to change the direction of log. I have a update to also change the `ctx.path`, so we can keep rotation in new direction.

I'm using `log2` in multiple threads context, you can see my demo video below. Everything works good
[log2.webm](https://github.com/sweihub/log2/assets/126753419/6708e2b4-19c0-44bf-97bd-f39bc14e0cc3)

**Review by williamdes — APPROVED** [review]

**Comment by sweihub** [comment]
Hello boss, sorry for the delay, it seems very close to our discussion & agreement now, could you add a test to `tests` directory which verify your feature? I hope to share your contributions to other guys to make life better.

**Comment by TuEmb** [comment]
Thanks for your reply, I have just updated `redirect` feature to create the log file before we redirect the path. Because it has an error when the new log file doesn't exist. And I also added the test case for it.

**Pull request merged**
